# this file has example values
services:
  jail-mcp:
    build: .
    container_name: jail-mcp-stdio
    image: ghcr.io/rthomazel/jail-mcp:latest
    stdin_open: true
    tty: false
    environment:
      JAIL_MCP_TIMEOUT: 15s
      JAIL_MCP_BACKGROUND_TIMEOUT: 5m
    volumes:
      # projects
      - /Users/you/helloworld:/projects/helloworld
      # :ro adds a path as read-only, must be after parent path
      #- /Users/you/helloworld/.git:/projects/helloworld/.git:ro
      - /Users/you/fizzbuzz:/projects/fizzbuzz
      #- /Users/you/fizzbuzz/.git:/projects/fizzbuzz/.git:ro
