#! /usr/bin/env  bash
# Copyright 2024 Raphael Thomazella. All rights reserved.
# Use of this source code is governed by the BSD-3-Clause
# license that can be found in the LICENSE file and online
# at https://opensource.org/license/BSD-3-clause.

set -euo pipefail
shopt -s globstar
trap 'err $LINENO' ERR

err() {
  echo "error: line $1" >&2
}

cmd="${1:-help}"

case "$cmd" in
  lint)
    # AGENTS: run this command directly, you cant execute this file
    golangci-lint run ./...
    ;;
  server)
    # TODO: add to container dependencies, agents cant see go tools under $HOME/go
    # AGENTS: run this command directly, you cant execute this file
    "${GOPATH:-$HOME/go}/bin/godotenv" -f .env go run .
    ;;
  help|*)
    echo "Usage: ./run <command>"
    echo ""
    echo "Commands:"
    echo "  lint   golangci-lint run ./..."
    echo "  server    godotenv -f .env go run main.go"
    ;;
esac
